### ISSUE TITLE
Start inactive domain

### ISSUE THREAD

**Issue by michaeljs1990** [rgbkrk/libvirt-go#108]
I must be blind but can't figure out how to do run `virsh start some_domain` from these bindings.

**Comment by vincentbernat** [comment]
Retrieve the domain with whatever method you want, then use `Create()` or `CreateWithFlags()`.

**Comment by michaeljs1990** [comment]
awesome, thanks. I did indeed see that but through that because `virsh create inactive-domain` from the cli on an inactive domain throws an error it would have the same functionality.

**Comment by hinesmr** [comment]
@michaeljs1990 That's a good point. The naming looks to be wrong. Any chance you could make a PR with the right name? (Maybe don't phase out the old name, or just deprecated it) so that the names properly match up with the libvirt API?

**Comment by vincentbernat** [comment]
`virsh start` uses `virDomainCreateWithFlags()` and `virDomainCreate()`. `virsh create` expects an XML file for domain creation (and uses `virDomainCreateXML()`.

**Comment by hinesmr** [comment]
Aha, so it's named appropriately according to the API, not the command line. So we're doing the right thing. Thanks for the clarification =)
