### ISSUE TITLE
Add virConnectGetAllDomainStats

### ISSUE THREAD

**Issue by vtolstov** [rgbkrk/libvirt-go#48]
Please add virConnectGetAllDomainStats support

**Comment by Cretezy** [comment]
https://github.com/cd1/libvirt-golang has support

**Comment by vtolstov** [comment]
thanks, but i don't want to go again to C binding.

**Comment by Cretezy** [comment]
What do you mean?

**Comment by vtolstov** [comment]
Now i thinks about pure go libvirt connector
