### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by rgbkrk** [rgbkrk/libvirt-go#56]
Hey @alexzorin, saw the deprecation notice. I'd love to help maintain this following the [C4.1 contribution model](http://rfc.zeromq.org/spec:22). If you're open to it, I'm open to helping the project move along with the changes to cgo.

**Comment by PunKeel** [comment]
? Is that a no, @alexzorin?

**Comment by alexzorin** [comment]
@PunKeel rgbkrk has agreed to take over the repo, I have transferred ownership

**Comment by PunKeel** [comment]
Oh, you're right, didn't notice.

Thanks! :+1:
