### ISSUE TITLE
Add virStoragePoolListAllVolumes

### ISSUE THREAD

**Issue by Cretezy** [rgbkrk/libvirt-go#60]
It is very similar to https://libvirt.org/html/libvirt-libvirt-storage.html#virConnectListAllStoragePools

I can't get it to work on my local machine as I can't find the libvirt-dev for my distro sadly.

**Comment by Cretezy** [comment]
Current workaround for me is to have a file with a list with volume's name. It's quite simple but it works, but it'd be nicer if it was build it, as the API is already there.

**Comment by Cretezy** [comment]
Moved to https://github.com/cd1/libvirt-golang as it implements the whole API (plus better flag support).

**Comment by rgbkrk** [comment]
> Moved to https://github.com/cd1/libvirt-golang as it implements the whole API (plus better flag support).

Nice! Thanks for reporting.
