### ISSUE TITLE
error fatal error: libvirt/libvirt-qemu.h: No such file or directory

### ISSUE THREAD

**Issue by torfuzx** [rgbkrk/libvirt-go#63]
Hi
When I go get github.com/rgbkrk/libvirt-go,appear a note '../github.com/rgbkrk/libvirt-go/cfuncs.go:5:29: fatal error: libvirt/libvirt.h: No such file or directory'.

My pc: Fedora 22.

**Comment by feiskyer** [comment]
@torfuzx  Have you installed `libvirt-devel`?

**Comment by torfuzx** [comment]
thank you

**Comment by derekwzheng** [comment]
Thanks!
Run
```$ sudo apt-get install libvirt-dev```
