### ISSUE TITLE
add virDomainUpdateDeviceFlags

### ISSUE THREAD

**Issue by clementino** [rgbkrk/libvirt-go#82]
Is it possible to add the virDomainUpdateDeviceFlags function?
(I think it was introduced before version 1.2.2)

I tried to change the media in an existing cdrom device using AttachDeviceFlags but it fails with a "target already exists" error, even tough the documentation says that it could be done for compatibility.

I succeeded by adding this function (copied from AttachDeviceFlags):
```
func (d *VirDomain) UpdateDeviceFlags(xml string, flags uint) error {
    cXml := C.CString(xml)
    defer C.free(unsafe.Pointer(cXml))
    result := C.virDomainUpdateDeviceFlags(d.ptr, cXml, C.uint(flags))
    if result == -1 {
        return GetLastError()
    }
    return nil
}
```
Thanks

**Comment by vincentbernat** [comment]
The call was introduced in 0.8.0, so it should be OK. If you could do a PR with a test, it would be great.

**Comment by vincentbernat** [comment]
Oh, this is already present.
