### ISSUE TITLE
problems in VirConnection.DomainEventRegister

### ISSUE THREAD

**Issue by clementino** [rgbkrk/libvirt-go#98]
1) In the switch in events.go#423 there are 3 empty cases (VIR_DOMAIN_EVENT_ID_REBOOT, VIR_DOMAIN_EVENT_ID_PMWAKEUP, VIR_DOMAIN_EVENT_ID_PMSUSPEND) which I think they are probably meant to have a fallthrough in them.

Currently if I pass such values for eventId I always get -1 from DomainEventRegister.

2) in events.go#457 in the call to C.virConnectDomainEventRegisterAny_cgo, C.VIR_DOMAIN_EVENT_ID_LIFECYCLE is hardcoded, shouldn't it be something like C.int(eventId)?

Currently if I pass anything but VIR_DOMAIN_EVENT_ID_LIFECYCLE as eventId to DomainEventRegister I always get a panic at the first dom state change.

**Comment by vincentbernat** [comment]
It may be fixed in #80. It would be good to extract the necessary bits from this PR.

**Comment by clementino** [comment]
I need to look better into that PR to understand it, but I don't see how it could work for all possible event types because some of the cases were simply removed (e.g. I need VIR_DOMAIN_EVENT_ID_REBOOT) so that they are caught by the default clause and fail.
But at least the eventID argument to C.virConnectDomainEventRegisterAny_cgo is changed so that it is not hardcoded anymore.

I think that having fallthroughs in the currently empty cases of that switch was obviously the intent of whoever wrote them (look at how they are grouped, and they make no sense otherwise).

Also the hardcoded eventId can't be right, and I don't see why we can't just pass DomainEventRegister's eventId through to C.virConnectDomainEventRegisterAny_cgo.

As I said I need to look better to understand what problems are left, but the two above look to me like obvious oversights, and by fixing both I was able to handle VIR_DOMAIN_EVENT_ID_REBOOT without problems so far.

Such change would not affect the behavior of DomainEventRegister in any way if the event type is VIR_DOMAIN_EVENT_ID_LIFECYCLE, which currently is the only one working, therefore I would propose to make it.
